# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Test

on:
  push:
    branches: [ master, ac/work1 ]
  pull_request:
    branches: [ master ]

#on:
#  release:
#    types: [created]

jobs:
  build:

    environment: dev

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file


      - name: Build with Maven
#        working-directory: github-actions-java-maven
        run: mvn -DMONGODB_SRV_USERNAME=${{ secrets.MONGODB_SRV_USERNAME }} -DMONGODB_SRV_PASSWORD=${{ secrets.MONGODB_SRV_PASSWORD }} -DMONGODB_SRV_DATABASE=${{ secrets.MONGODB_SRV_DATABASE }} -B package --file pom.xml

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact.jar
          path: ./target/application.jar
#          path: github-actions-java-maven/target/github-actions-java-maven.jar

#      - name: Publish to GitHub Packages Apache Maven
#        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
